In [2]:
import pandas as pd
import numpy as np
import keras
import tensorflow as tf
from keras.layers import Dense
from keras.layers import Conv2D
from keras.layers import MaxPool2D
from keras.layers import Dropout
from keras.models import Sequential
from keras.layers import Flatten

In [3]:
import cifar10
import matplotlib.pyplot as plt

In [4]:
cifar10.data_path = "data/CIFAR-10/"

In [5]:
cifar10.maybe_download_and_extract()

Data has apparently already been downloaded and unpacked.


In [6]:
class_names = cifar10.load_class_names()
class_names

Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [7]:
images_train, cls_train, labels_train = cifar10.load_training_data()
images_test, cls_test, labels_test = cifar10.load_test_data()

Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch


In [8]:
print(images_train.shape)
print(cls_train)
print(labels_train.shape)

(50000, 32, 32, 3)
[6 9 9 ... 9 1 1]
(50000, 10)


In [10]:
model=Sequential()
model.add(Conv2D(32,(3,3),activation="relu",padding="same",input_shape=(32,32,3)))
model.add(Conv2D(32,(3,3),activation="relu"))
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Conv2D(64,(3,3),activation="relu",padding="same"))
model.add(Conv2D(64,(3,3),activation="relu"))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())

model.add(Dense(512,activation="relu"))
model.add(Dropout(0.5))

model.add(Dense(10,activation="softmax"))

In [11]:
opt = keras.optimizers.Adam(learning_rate=1.0e-4)
model.compile(optimizer=opt,loss="categorical_crossentropy",metrics=["accuracy"])

In [12]:
model.fit(images_train,labels_train,batch_size=128,epochs=100,validation_data=(images_test,labels_test))


Train on 50000 samples, validate on 10000 samples
Epoch 1/100
50000/50000 [==============================] - 171s 3ms/step - loss: 1.8619 - accuracy: 0.3194 - val_loss: 1.5633 - val_accuracy: 0.4346
Epoch 2/100
50000/50000 [==============================] - 166s 3ms/step - loss: 1.5424 - accuracy: 0.4397 - val_loss: 1.3940 - val_accuracy: 0.4976
Epoch 3/100
50000/50000 [==============================] - 166s 3ms/step - loss: 1.4148 - accuracy: 0.4906 - val_loss: 1.2912 - val_accuracy: 0.5431
Epoch 4/100
50000/50000 [==============================] - 165s 3ms/step - loss: 1.3211 - accuracy: 0.5300 - val_loss: 1.2582 - val_accuracy: 0.5574
Epoch 5/100
50000/50000 [==============================] - 163s 3ms/step - loss: 1.2596 - accuracy: 0.5548 - val_loss: 1.1694 - val_accuracy: 0.5881
Epoch 6/100
50000/50000 [==============================] - 133s 3ms/step - loss: 1.2050 - accuracy: 0.5728 - val_loss: 1.1346 - val_accuracy: 0.6025
Epoch 7/100
50000/50000 [==============================

Epoch 54/100
50000/50000 [==============================] - 135s 3ms/step - loss: 0.4429 - accuracy: 0.8441 - val_loss: 0.6645 - val_accuracy: 0.7757
Epoch 55/100
50000/50000 [==============================] - 145s 3ms/step - loss: 0.4337 - accuracy: 0.8471 - val_loss: 0.6763 - val_accuracy: 0.7736
Epoch 56/100
50000/50000 [==============================] - 136s 3ms/step - loss: 0.4206 - accuracy: 0.8523 - val_loss: 0.6566 - val_accuracy: 0.7805
Epoch 57/100
50000/50000 [==============================] - 135s 3ms/step - loss: 0.4144 - accuracy: 0.8529 - val_loss: 0.6792 - val_accuracy: 0.7748
Epoch 58/100
50000/50000 [==============================] - 142s 3ms/step - loss: 0.4086 - accuracy: 0.8553 - val_loss: 0.6631 - val_accuracy: 0.7767
Epoch 59/100
50000/50000 [==============================] - 155s 3ms/step - loss: 0.4018 - accuracy: 0.8592 - val_loss: 0.6718 - val_accuracy: 0.7726
Epoch 60/100
50000/50000 [==============================] - 152s 3ms/step - loss: 0.3919 - accuracy:

In [13]:
predictions=model.predict(images_test)

In [14]:
score=model.evaluate(images_test,labels_test)
score

10000/10000 [==============================] - 10s 975us/step


[0.7259844159126282, 0.7874000072479248]

In [15]:
predictions.shape

(10000, 10)

In [16]:
pred=[]
for ele in predictions:
    pred.append(ele.argmax())

In [17]:
pred=np.reshape(pred,(10000,1))

In [18]:
pred

array([[3],
       [8],
       [8],
       ...,
       [5],
       [0],
       [7]], dtype=int64)

In [19]:
predictions=model.predict(images_test)

In [20]:
score=model.evaluate(images_test,labels_test)
score

10000/10000 [==============================] - 11s 1ms/step


[0.7259844159126282, 0.7874000072479248]

In [21]:
pred=[]
for ele in predictions:
    pred.append(ele.argmax())

In [22]:
pred=np.reshape(pred,(10000,1))

In [23]:
pred

array([[3],
       [8],
       [8],
       ...,
       [5],
       [0],
       [7]], dtype=int64)

In [24]:
new_pred=[]
for ele in pred:
    new_pred.append(class_names[ele[0]])

In [25]:
new_pred

['cat',
 'ship',
 'ship',
 'airplane',
 'frog',
 'frog',
 'automobile',
 'frog',
 'cat',
 'automobile',
 'airplane',
 'truck',
 'dog',
 'horse',
 'truck',
 'ship',
 'dog',
 'horse',
 'ship',
 'frog',
 'horse',
 'airplane',
 'deer',
 'truck',
 'deer',
 'cat',
 'deer',
 'airplane',
 'truck',
 'frog',
 'frog',
 'dog',
 'deer',
 'cat',
 'truck',
 'truck',
 'deer',
 'automobile',
 'truck',
 'dog',
 'deer',
 'frog',
 'dog',
 'frog',
 'airplane',
 'truck',
 'cat',
 'truck',
 'horse',
 'frog',
 'truck',
 'ship',
 'frog',
 'cat',
 'ship',
 'ship',
 'cat',
 'cat',
 'cat',
 'dog',
 'horse',
 'dog',
 'frog',
 'cat',
 'frog',
 'bird',
 'automobile',
 'bird',
 'dog',
 'horse',
 'cat',
 'frog',
 'ship',
 'ship',
 'airplane',
 'bird',
 'airplane',
 'cat',
 'cat',
 'ship',
 'ship',
 'automobile',
 'automobile',
 'horse',
 'bird',
 'horse',
 'bird',
 'bird',
 'ship',
 'truck',
 'airplane',
 'bird',
 'ship',
 'frog',
 'deer',
 'frog',
 'frog',
 'airplane',
 'airplane',
 'horse',
 'deer',
 'dog',
 'frog',

In [26]:
new_pred=np.reshape(new_pred,(10000,1))

In [27]:
np.savetxt('cifar.csv', new_pred, delimiter=',',fmt='%s')